apiVersion: v1
kind: Service
metadata:
  name: igp-backend-ticket-app
spec:
  selector:
    app: igp-backend-ticket-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer